name: Test and raise PRto Main Branch
on:
  push:
    branches:
      - dev-branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # You can specify your preferred Node.js version here

      - name: Install dependencies
        run: cd backend && npm install
        
      - name: Install dependencies
        run: cd frontent && npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: "Automated PR from dev to main"
          body: "This PR was automatically created when tests passed on the dev branch."
